In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

In [75]:
df_madrid = pd.read_csv("madrid.csv")
df_rome = pd.read_csv("rome.csv")
df_paris = pd.read_csv("paris.csv")
df_oslo = pd.read_csv("oslo.csv")
df_london = pd.read_csv("london.csv")
df_geneva = pd.read_csv("geneva.csv")
df_dublin = pd.read_csv("dublin.csv")
df_barcelona = pd.read_csv("barcelona.csv")
df_athens = pd.read_csv("athens.csv")
df_amsterdam = pd.read_csv("amsterdam.csv")


l_dataframes = [df_madrid, df_barcelona, df_rome, df_paris, df_oslo, df_london, df_geneva, df_dublin, df_athens, df_amsterdam]

In [76]:
df_madrid["city"] = "madrid"
df_rome["city"] = "rome"
df_paris["city"] = "paris"
df_oslo["city"] = "oslo"
df_london["city"] = "london"
df_geneva["city"] = "geneva"
df_dublin["city"] = "dublin"
df_barcelona["city"] = "barcelona"
df_athens["city"] = "athens"
df_amsterdam["city"] = "amsterdam"

In [77]:
df_madrid

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
0,6369,https://www.airbnb.com/rooms/6369,20220911230855,2022-09-12,city scrape,"Rooftop terrace room , ensuite bathroom",Excellent connection with the AIRPORT and EXHI...,NaN,https://a0.muscache.com/pictures/683224/4cc318...,13660,...,4.82,4.85,NaN,f,1,0,1,0,0.65,madrid
1,21853,https://www.airbnb.com/rooms/21853,20220911230855,2022-09-12,city scrape,Bright and airy room,We have a quiet and sunny room with a good vie...,We live in a leafy neighbourhood with plenty o...,https://a0.muscache.com/pictures/68483181/87bc...,83531,...,4.21,4.67,NaN,f,2,0,2,0,0.34,madrid
2,24805,https://www.airbnb.com/rooms/24805,20220911230855,2022-09-12,city scrape,Gran Via Studio Madrid,"Studio located 50 meters from Gran Via, next t...","The area is next to the Gran Via, so people li...",https://a0.muscache.com/pictures/miso/Hosting-...,346366726,...,5.00,4.83,NaN,f,1,1,0,0,0.25,madrid
3,26825,https://www.airbnb.com/rooms/26825,20220911230855,2022-09-12,city scrape,Single Room whith private Bathroom,Nice and cozy roon for one person with a priva...,"Es un barrio muy tranquilo, en una zona de Mad...",https://a0.muscache.com/pictures/149358/218d5b...,114340,...,4.73,4.74,NaN,f,1,0,1,0,1.10,madrid
4,363476,https://www.airbnb.com/rooms/363476,20220911230855,2022-09-12,city scrape,PUERTA DEL SOL-QUIET DOWNTOWN,<b>The space</b><br />We want to welcome this ...,NaN,https://a0.muscache.com/pictures/4264879/ee070...,1836617,...,4.97,4.52,NaN,f,1,0,1,0,3.74,madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20676,50986852,https://www.airbnb.com/rooms/50986852,20220911230855,2022-09-12,city scrape,Precioso apartamento para 5 personas,Disfruta de la sencillez de este alojamiento t...,NaN,https://a0.muscache.com/pictures/b2da2e0f-3c5c...,17074819,...,4.00,5.00,NaN,f,5,2,3,0,0.59,madrid
20677,16486548,https://www.airbnb.com/rooms/16486548,20220911230855,2022-09-12,city scrape,"Amplio, luminoso y confortable",Espectacular piso compartido decoracion modern...,NaN,https://a0.muscache.com/pictures/3b89555a-530d...,30696902,...,4.00,4.00,NaN,f,8,2,6,0,0.36,madrid
20678,11961106,https://www.airbnb.com/rooms/11961106,20220911230855,2022-09-12,city scrape,Getafe Carlos III University,"The house is located in the center of Getafe ,...",NaN,https://a0.muscache.com/pictures/1367b7db-14d5...,63883696,...,4.65,4.82,NaN,f,1,0,1,0,0.24,madrid
20679,43692572,https://www.airbnb.com/rooms/43692572,20220911230855,2022-09-12,city scrape,Precioso Duplex con encanto en Pozuelo,Precioso Duplex de 2 habitaciones listo para r...,"Ubicado en la zona de la Avenida de Europa, en...",https://a0.muscache.com/pictures/61131c33-f557...,85797262,...,4.83,4.67,NaN,f,2,1,1,0,0.44,madrid
20680,50808000,https://www.airbnb.com/rooms/50808000,20220911230855,2022-09-12,city scrape,Precioso apartamento en Alcorcón,Relájate y desconecta en este alojamiento tran...,NaN,https://a0.muscache.com/pictures/8031c073-685e...,409085640,...,4.50,5.00,NaN,t,1,1,0,0,0.14,madrid

In [78]:
for i in l_dataframes:
    i.drop("source", axis = 1, inplace = True)

In [79]:
for i in l_dataframes:
    print(i.shape)

(20681, 75)
(16920, 75)
(24782, 75)
(61365, 75)
(5371, 75)
(69351, 75)
(3370, 75)
(7566, 75)
(12165, 75)
(6893, 75)

In [80]:
df = pd.concat(l_dataframes)
df

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
0,6369,https://www.airbnb.com/rooms/6369,20220911230855,2022-09-12,"Rooftop terrace room , ensuite bathroom",Excellent connection with the AIRPORT and EXHI...,NaN,https://a0.muscache.com/pictures/683224/4cc318...,13660,https://www.airbnb.com/users/show/13660,...,4.82,4.85,NaN,f,1,0,1,0,0.65,madrid
1,21853,https://www.airbnb.com/rooms/21853,20220911230855,2022-09-12,Bright and airy room,We have a quiet and sunny room with a good vie...,We live in a leafy neighbourhood with plenty o...,https://a0.muscache.com/pictures/68483181/87bc...,83531,https://www.airbnb.com/users/show/83531,...,4.21,4.67,NaN,f,2,0,2,0,0.34,madrid
2,24805,https://www.airbnb.com/rooms/24805,20220911230855,2022-09-12,Gran Via Studio Madrid,"Studio located 50 meters from Gran Via, next t...","The area is next to the Gran Via, so people li...",https://a0.muscache.com/pictures/miso/Hosting-...,346366726,https://www.airbnb.com/users/show/346366726,...,5.00,4.83,NaN,f,1,1,0,0,0.25,madrid
3,26825,https://www.airbnb.com/rooms/26825,20220911230855,2022-09-12,Single Room whith private Bathroom,Nice and cozy roon for one person with a priva...,"Es un barrio muy tranquilo, en una zona de Mad...",https://a0.muscache.com/pictures/149358/218d5b...,114340,https://www.airbnb.com/users/show/114340,...,4.73,4.74,NaN,f,1,0,1,0,1.10,madrid
4,363476,https://www.airbnb.com/rooms/363476,20220911230855,2022-09-12,PUERTA DEL SOL-QUIET DOWNTOWN,<b>The space</b><br />We want to welcome this ...,NaN,https://a0.muscache.com/pictures/4264879/ee070...,1836617,https://www.airbnb.com/users/show/1836617,...,4.97,4.52,NaN,f,1,0,1,0,3.74,madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6888,12690380,https://www.airbnb.com/rooms/12690380,20220907151523,2022-09-07,"Amsterdam, light big house 15 min from citycenter",We have a comfortable cosy house with a garden...,Green and quiet lots of playgrounds for kids o...,https://a0.muscache.com/pictures/a100d408-769c...,15032494,https://www.airbnb.com/users/show/15032494,...,4.63,4.75,NaN,f,1,1,0,0,0.36,amsterdam
6889,15005354,https://www.airbnb.com/rooms/15005354,20220907151523,2022-09-07,Perfect family home near Amsterdam,Our house is situated in a quiet neighborhood ...,The house is situated in a beautiful neighbour...,https://a0.muscache.com/pictures/7a7d8058-c3f7...,46437958,https://www.airbnb.com/users/show/46437958,...,4.89,4.83,NaN,f,1,1,0,0,0.26,amsterdam
6890,15171981,https://www.airbnb.com/rooms/15171981,20220907151523,2022-09-07,Child friendly house near Amsterdam - free par...,Lovely family house with beautiful garden in a...,"Located just outside of Amsterdam, in Duivendr...",https://a0.muscache.com/pictures/50ab12e8-c478...,96286859,https://www.airbnb.com/users/show/96286859,...,4.30,4.50,NaN,f,1,1,0,0,0.29,amsterdam
6891,17567812,https://www.airbnb.com/rooms/17567812,20220907151523,2022-09-07,"Modern, spacious family home, 5 bedrooms-Amste...",Our house is located just 10 minutes away from...,"A very nice, quiet area, close to a park, fore...",https://a0.muscache.com/pictures/89bba873-f6c1...,55072916,https://www.airbnb.com/users/show/55072916,...,4.75,4.88,NaN,f,1,1,0,0,0.12,amsterdam
6892,20084434,https://www.airbnb.com/rooms/20084434,20220907151523,2022-09-07,Single-family house (15m cycling center Amster...,"Careful! The house has one double bed, one sin...",This is a little peace and quiet in the crazin...,https://a0.muscache.com/pictures/b68d763a-2c1f...,29435851,https://www.airbnb.com/users/show/29435851,...,4.82,4.68,NaN,f,1,1,0,0,0.37,amsterdam

In [81]:
# df[["reviews_per_month"]]
# df["reviews_per_month"] = df["reviews_per_month"].fillna(df["reviews_per_month"].mean())

In [82]:
# df["reviews_per_month"]

# from sklearn.impute import KNNImputer

# imputer = KNNImputer(n_neighbors = 3)

# df_num_imp = imputer.fit_transform(df[["reviews_per_month"]])

# df["reviews_per_month"] = df_num_imp

In [83]:
columns_drop = ["listing_url", "scrape_id", "last_scraped", "description", "picture_url", "host_url", "host_about",
                "host_location", "name", "neighborhood_overview", "host_since", "host_thumbnail_url", "host_picture_url",
                "host_neighbourhood", "host_listings_count", "host_has_profile_pic", "bathrooms", "calendar_updated",
                "has_availability", "calendar_last_scraped", "number_of_reviews_ltm", "number_of_reviews_l30d",
                "first_review", "last_review", "review_scores_rating", "review_scores_accuracy", "review_scores_cleanliness",
                "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value",
                "license", "calculated_host_listings_count_entire_homes", "calculated_host_listings_count_private_rooms",
                "calculated_host_listings_count_shared_rooms", "neighbourhood", "host_name", "calculated_host_listings_count"]

columns_maybe_drop = ["host_response_time", "host_response_rate", "host_acceptance_rate", "host_is_superhost",
                      "host_identity_verified", "minimum_minimum_nights", "minimum_minimum_nights", "maximum_minimum_nights",
                      "minimum_maximum_nights", "maximum_maximum_nights", "minimum_nights_avg_ntm", "maximum_nights_avg_ntm",
                      "availability_30", "availability_60", "availability_90"]

In [84]:
df.drop(columns = columns_drop + columns_maybe_drop, axis = 1, inplace = True)

In [85]:
df.isna().sum()/df.shape[0]*100

id                               0.000000
host_id                          0.000000
host_total_listings_count        0.010505
host_verifications               0.000000
neighbourhood_cleansed           0.000000
neighbourhood_group_cleansed    83.541827
latitude                         0.000000
longitude                        0.000000
property_type                    0.000000
room_type                        0.000000
accommodates                     0.000000
bathrooms_text                   0.167641
bedrooms                         8.010452
beds                             1.594124
amenities                        0.000000
price                            0.000000
minimum_nights                   0.000000
maximum_nights                   0.000000
availability_365                 0.000000
number_of_reviews                0.000000
instant_bookable                 0.000000
reviews_per_month               20.056552
city                             0.000000
dtype: float64

In [86]:
# host_verifications: número de elementos en la lista
df["host_verifications"] = df["host_verifications"].apply(lambda x : len(json.loads((x.replace("'", '"')))) if x != "None" else np.nan)

In [87]:
# bathrooms_text: limpieza de columna

df["bathrooms_text"] = df["bathrooms_text"].apply(lambda x : x.split(" ")[0] if (type(x) == str) and ("bath" in x) else np.nan)

bath_map = {"Private" : 1, "Shared" : 0.5, "Half-bath" : 0.5}

df["bathrooms_text"] = df["bathrooms_text"].apply(lambda x : bath_map[x] if x in bath_map.keys() else float(x))

In [88]:
# amenities: número de elementos en la lista

list_amenities = list()

for num, x in enumerate(df["amenities"].values):
    try:
        list_amenities.append(len(json.loads((x.replace("'", '"')))))
        
    except:
        list_amenities.append(len(x.replace("'", '"').replace("\\", "")))
        
        
df["amenities"] = list_amenities

In [89]:
# Quito esta columna por la cantidad de NaN's, pero creo que si estuviera el modelo daría mejores resultados
# Se pueden llenar con KNNImputer

#df.drop("reviews_per_month", axis = 1, inplace = True)
df.dropna(inplace = True)

In [90]:
df

,id,host_id,host_total_listings_count,host_verifications,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,...,beds,amenities,price,minimum_nights,maximum_nights,availability_365,number_of_reviews,instant_bookable,reviews_per_month,city
0,6369,13660,1.0,2.0,Hispanoamérica,Chamartín,40.45724,-3.67688,Private room in rental unit,Private room,...,1.0,37,$77.00,3,1125,56,99,f,0.65,madrid
1,21853,83531,2.0,2.0,Cármenes,Latina,40.40381,-3.74130,Private room in rental unit,Private room,...,1.0,27,$31.00,4,40,255,33,f,0.34,madrid
3,26825,114340,4.0,2.0,Legazpi,Arganzuela,40.38975,-3.69018,Private room in home,Private room,...,1.0,14,$26.00,2,1125,339,166,f,1.10,madrid
4,363476,1836617,1.0,3.0,Sol,Centro,40.41676,-3.70682,Private room in rental unit,Private room,...,1.0,18,$49.00,2,90,271,475,f,3.74,madrid
5,30320,130907,6.0,2.0,Sol,Centro,40.41476,-3.70418,Entire rental unit,Entire home/apt,...,2.0,8,$120.00,5,180,353,171,f,1.15,madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16915,26383234,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37377,2.11757,Private room in hostel,Private room,...,6.0,28,"$5,000.00",1,10,0,30,f,0.59,barcelona
16916,26383143,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37377,2.11757,Private room in hostel,Private room,...,6.0,28,"$5,000.00",1,10,0,2,f,0.05,barcelona
16917,26384664,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37411,2.11852,Private room in hostel,Private room,...,6.0,30,"$5,000.00",1,10,0,13,f,0.33,barcelona
16918,18220085,10030977,2.0,3.0,Pedralbes,Les Corts,41.38844,2.08789,Entire home,Entire home/apt,...,5.0,37,$250.00,6,1125,0,12,f,0.19,barcelona
16919,5122846,1145453,6.0,3.0,"Vallvidrera, el Tibidabo i les Planes",Sarrià-Sant Gervasi,41.38510,2.07642,Private room in villa,Private room,...,1.0,80,$33.00,1,5,0,5,f,0.06,barcelona

In [91]:
df_num = df._get_numeric_data()
df_num

,id,host_id,host_total_listings_count,host_verifications,latitude,longitude,accommodates,bathrooms_text,bedrooms,beds,amenities,minimum_nights,maximum_nights,availability_365,number_of_reviews,reviews_per_month
0,6369,13660,1.0,2.0,40.45724,-3.67688,2,1.0,1.0,1.0,37,3,1125,56,99,0.65
1,21853,83531,2.0,2.0,40.40381,-3.74130,1,1.0,1.0,1.0,27,4,40,255,33,0.34
3,26825,114340,4.0,2.0,40.38975,-3.69018,1,1.0,1.0,1.0,14,2,1125,339,166,1.10
4,363476,1836617,1.0,3.0,40.41676,-3.70682,2,1.5,1.0,1.0,18,2,90,271,475,3.74
5,30320,130907,6.0,2.0,40.41476,-3.70418,2,1.0,1.0,2.0,8,5,180,353,171,1.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16915,26383234,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,28,1,10,0,30,0.59
16916,26383143,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,28,1,10,0,2,0.05
16917,26384664,198281707,12.0,2.0,41.37411,2.11852,6,1.5,1.0,6.0,30,1,10,0,13,0.33
16918,18220085,10030977,2.0,3.0,41.38844,2.08789,5,2.0,4.0,5.0,37,6,1125,0,12,0.19
16919,5122846,1145453,6.0,3.0,41.38510,2.07642,1,1.0,1.0,1.0,80,1,5,0,5,0.06

In [92]:
# Agrego la columna id para después hacer pd.merge()

df_cat = df.drop(df_num.columns, axis = 1)
df_cat = pd.concat([df_cat, df_num[["id"]]], axis = 1)
df_cat

,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,price,instant_bookable,city,id
0,Hispanoamérica,Chamartín,Private room in rental unit,Private room,$77.00,f,madrid,6369
1,Cármenes,Latina,Private room in rental unit,Private room,$31.00,f,madrid,21853
3,Legazpi,Arganzuela,Private room in home,Private room,$26.00,f,madrid,26825
4,Sol,Centro,Private room in rental unit,Private room,$49.00,f,madrid,363476
5,Sol,Centro,Entire rental unit,Entire home/apt,$120.00,f,madrid,30320
...,...,...,...,...,...,...,...,...
16915,la Maternitat i Sant Ramon,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26383234
16916,la Maternitat i Sant Ramon,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26383143
16917,la Maternitat i Sant Ramon,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26384664
16918,Pedralbes,Les Corts,Entire home,Entire home/apt,$250.00,f,barcelona,18220085
16919,"Vallvidrera, el Tibidabo i les Planes",Sarrià-Sant Gervasi,Private room in villa,Private room,$33.00,f,barcelona,5122846

In [93]:
# Decido quedarme solo con "neighbourhood_group_cleansed"

df_cat.drop(["neighbourhood_cleansed"], axis = 1, inplace = True)

df_cat

,neighbourhood_group_cleansed,property_type,room_type,price,instant_bookable,city,id
0,Chamartín,Private room in rental unit,Private room,$77.00,f,madrid,6369
1,Latina,Private room in rental unit,Private room,$31.00,f,madrid,21853
3,Arganzuela,Private room in home,Private room,$26.00,f,madrid,26825
4,Centro,Private room in rental unit,Private room,$49.00,f,madrid,363476
5,Centro,Entire rental unit,Entire home/apt,$120.00,f,madrid,30320
...,...,...,...,...,...,...,...
16915,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26383234
16916,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26383143
16917,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26384664
16918,Les Corts,Entire home,Entire home/apt,$250.00,f,barcelona,18220085
16919,Sarrià-Sant Gervasi,Private room in villa,Private room,$33.00,f,barcelona,5122846

In [94]:
# price: limpieza de columna
df_cat["price"] = df_cat["price"].apply(lambda x : float(x.strip("$").replace(",", "")))

In [95]:
# instant_bookable: transformar a 0 y 1
df_cat["instant_bookable"] = df_cat["instant_bookable"].apply(lambda x : 0 if x == "f" else 1)

In [96]:
# room_type: eliminar "Hotel room" y transformar a dummies

df_cat = df_cat[df_cat["room_type"] != "Hotel room"]

df_cat = pd.concat([df_cat, pd.get_dummies(data = df_cat["room_type"])], axis = 1).drop("room_type", axis = 1)

In [97]:
df_cat

,neighbourhood_group_cleansed,property_type,price,instant_bookable,city,id,Entire home/apt,Private room,Shared room
0,Chamartín,Private room in rental unit,77.0,0,madrid,6369,0,1,0
1,Latina,Private room in rental unit,31.0,0,madrid,21853,0,1,0
3,Arganzuela,Private room in home,26.0,0,madrid,26825,0,1,0
4,Centro,Private room in rental unit,49.0,0,madrid,363476,0,1,0
5,Centro,Entire rental unit,120.0,0,madrid,30320,1,0,0
...,...,...,...,...,...,...,...,...,...
16915,Les Corts,Private room in hostel,5000.0,0,barcelona,26383234,0,1,0
16916,Les Corts,Private room in hostel,5000.0,0,barcelona,26383143,0,1,0
16917,Les Corts,Private room in hostel,5000.0,0,barcelona,26384664,0,1,0
16918,Les Corts,Entire home,250.0,0,barcelona,18220085,1,0,0
16919,Sarrià-Sant Gervasi,Private room in villa,33.0,0,barcelona,5122846,0,1,0

In [98]:
# property_type está representada port la columnas dummies de room_type

df_cat.drop("property_type", axis = 1, inplace = True)

In [99]:
# Uso el LabelEncoder para transformarlo a números sin ningún tipo de relación u orden

from sklearn.preprocessing import LabelEncoder

neighbourhood_group_encoder = LabelEncoder()
df_cat["neighbourhood_group_cleansed"] = neighbourhood_group_encoder.fit_transform(df_cat["neighbourhood_group_cleansed"])

In [100]:
from sklearn.preprocessing import LabelEncoder

neighbourhood_group_encoder = LabelEncoder()
df_cat["city"] = neighbourhood_group_encoder.fit_transform(df_cat["city"])

In [101]:
df = pd.merge(left = df_num, right = df_cat, on = "id")

df

,id,host_id,host_total_listings_count,host_verifications,latitude,longitude,accommodates,bathrooms_text,bedrooms,beds,...,availability_365,number_of_reviews,reviews_per_month,neighbourhood_group_cleansed,price,instant_bookable,city,Entire home/apt,Private room,Shared room
0,6369,13660,1.0,2.0,40.45724,-3.67688,2,1.0,1.0,1.0,...,56,99,0.65,4,77.0,0,1,0,1,0
1,21853,83531,2.0,2.0,40.40381,-3.74130,1,1.0,1.0,1.0,...,255,33,0.34,13,31.0,0,1,0,1,0
2,26825,114340,4.0,2.0,40.38975,-3.69018,1,1.0,1.0,1.0,...,339,166,1.10,0,26.0,0,1,0,1,0
3,363476,1836617,1.0,3.0,40.41676,-3.70682,2,1.5,1.0,1.0,...,271,475,3.74,3,49.0,0,1,0,1,0
4,30320,130907,6.0,2.0,40.41476,-3.70418,2,1.0,1.0,2.0,...,353,171,1.15,3,120.0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27305,26383234,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,0,30,0.59,14,5000.0,0,0,0,1,0
27306,26383143,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,0,2,0.05,14,5000.0,0,0,0,1,0
27307,26384664,198281707,12.0,2.0,41.37411,2.11852,6,1.5,1.0,6.0,...,0,13,0.33,14,5000.0,0,0,0,1,0
27308,18220085,10030977,2.0,3.0,41.38844,2.08789,5,2.0,4.0,5.0,...,0,12,0.19,14,250.0,0,0,1,0,0
27309,5122846,1145453,6.0,3.0,41.38510,2.07642,1,1.0,1.0,1.0,...,0,5,0.06,25,33.0,0,0,0,1,0

### Outliers

In [102]:
df

,id,host_id,host_total_listings_count,host_verifications,latitude,longitude,accommodates,bathrooms_text,bedrooms,beds,...,availability_365,number_of_reviews,reviews_per_month,neighbourhood_group_cleansed,price,instant_bookable,city,Entire home/apt,Private room,Shared room
0,6369,13660,1.0,2.0,40.45724,-3.67688,2,1.0,1.0,1.0,...,56,99,0.65,4,77.0,0,1,0,1,0
1,21853,83531,2.0,2.0,40.40381,-3.74130,1,1.0,1.0,1.0,...,255,33,0.34,13,31.0,0,1,0,1,0
2,26825,114340,4.0,2.0,40.38975,-3.69018,1,1.0,1.0,1.0,...,339,166,1.10,0,26.0,0,1,0,1,0
3,363476,1836617,1.0,3.0,40.41676,-3.70682,2,1.5,1.0,1.0,...,271,475,3.74,3,49.0,0,1,0,1,0
4,30320,130907,6.0,2.0,40.41476,-3.70418,2,1.0,1.0,2.0,...,353,171,1.15,3,120.0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27305,26383234,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,0,30,0.59,14,5000.0,0,0,0,1,0
27306,26383143,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,0,2,0.05,14,5000.0,0,0,0,1,0
27307,26384664,198281707,12.0,2.0,41.37411,2.11852,6,1.5,1.0,6.0,...,0,13,0.33,14,5000.0,0,0,0,1,0
27308,18220085,10030977,2.0,3.0,41.38844,2.08789,5,2.0,4.0,5.0,...,0,12,0.19,14,250.0,0,0,1,0,0
27309,5122846,1145453,6.0,3.0,41.38510,2.07642,1,1.0,1.0,1.0,...,0,5,0.06,25,33.0,0,0,0,1,0

In [103]:
df["bathrooms_text"] = df["bathrooms_text"].apply(lambda x : np.ceil(x))

In [104]:
# Eliminé outliers solo viendo las gráficas
# Elimino alrededor de 4000 filas (muchísimo)

df = df[df["accommodates"] <= 8]
df = df[df["bathrooms_text"].between(1, 2)]
df = df[df["bedrooms"] <= 4]
df = df[df["beds"].between(1, 5)]
df = df[df["amenities"] <= 50]
df = df[df["minimum_nights"] <= 30]
df = df[df["number_of_reviews"] <= 300]
df = df[df["reviews_per_month"] <= 8]
df = df[df["price"] <= 400]
# df = df[df["host_total_listings_count"] <= 40]

In [105]:
# Elimono "Shared room" por el desbalance, casí no aparace en comparación a los otros

df.drop("Shared room", axis = 1, inplace = True)

### Normalizar

In [106]:
from sklearn.preprocessing import MinMaxScaler

x_scaler = MinMaxScaler()
df[df.drop("price", axis = 1).columns] = x_scaler.fit_transform(df[df.drop("price", axis = 1).columns])

y_scaler = MinMaxScaler()
df["price"] = y_scaler.fit_transform(df[["price"]]).flatten()

In [107]:
df.drop(["host_id", "id", "latitude", "longitude"], axis = 1, inplace = True)

In [108]:
df.drop(["instant_bookable", "host_verifications"], axis = 1, inplace = True)

In [109]:
df.columns

Index(['host_total_listings_count', 'accommodates', 'bathrooms_text',
       'bedrooms', 'beds', 'amenities', 'minimum_nights', 'maximum_nights',
       'availability_365', 'number_of_reviews', 'reviews_per_month',
       'neighbourhood_group_cleansed', 'price', 'city', 'Entire home/apt',
       'Private room'],
      dtype='object')

In [110]:
X = df.drop(["price"], axis = 1)
y = df["price"]

print(X.shape, y.shape)

(20398, 15) (20398,)

### Train, Test

In [111]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print(f"X_train: {X_train.shape} | y_train: {y_train.shape}")
print(f"X_test: {X_test.shape} | y_test: {y_test.shape}")

X_train: (16318, 15) | y_train: (16318,)
X_test: (4080, 15) | y_test: (4080,)

### Modelos y Métricas

In [112]:
# Modelos
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor

# Métricas
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [113]:
%%time

modelos = [LinearRegression(), KNeighborsRegressor(), DecisionTreeRegressor(),
           RandomForestRegressor(), SVR(), AdaBoostRegressor(), GradientBoostingRegressor()]

metricas = list() 

for model in modelos:
    
    # fit
    model.fit(X_train, y_train)
    
    # predict
    yhat = model.predict(X_test)
    
    # metrics
    r2 = r2_score(y_test, yhat)
    mse = mean_squared_error(y_test, yhat)
    
    metricas.append([str(model), r2, mse, model])
    
df_metricas = pd.DataFrame(data = metricas, columns = ["model_name", "r2", "mse", "model"])

df_metricas.sort_values(by = "r2", ascending = False)

Wall time: 14.3 s

,model_name,r2,mse,model
3,RandomForestRegressor(),0.719627,0.011591,"(DecisionTreeRegressor(max_features='auto', ra..."
6,GradientBoostingRegressor(),0.653755,0.014314,([DecisionTreeRegressor(criterion='friedman_ms...
4,SVR(),0.638205,0.014957,SVR()
1,KNeighborsRegressor(),0.607139,0.016241,KNeighborsRegressor()
0,LinearRegression(),0.546996,0.018728,LinearRegression()
2,DecisionTreeRegressor(),0.459035,0.022364,DecisionTreeRegressor()
5,AdaBoostRegressor(),0.444787,0.022953,"(DecisionTreeRegressor(max_depth=3, random_sta..."

In [114]:
modelo = df_metricas["model"][3]

modelo

RandomForestRegressor()

In [115]:
importances = np.argsort(modelo.feature_importances_)[::-1]

for i in importances:
    
    print(i, modelo.feature_importances_[i]*100, df.drop("price", axis = 1).columns[i])

1 31.224810485028353 accommodates
0 11.166900658773102 host_total_listings_count
12 7.974381712966442 city
8 7.961453041547643 availability_365
13 7.120031223792285 Entire home/apt
10 6.302766087989428 reviews_per_month
5 5.323874176312625 amenities
9 4.426751750017302 number_of_reviews
6 4.313447679034568 minimum_nights
11 4.124460963618548 neighbourhood_group_cleansed
2 3.453722968601612 bathrooms_text
7 3.3182462198585436 maximum_nights
3 1.6837536842525789 bedrooms
4 1.4459233847416515 beds
14 0.15947596346531903 Private room

In [116]:
modelo = df_metricas["model"][6]

importances = np.argsort(modelo.feature_importances_)[::-1]

for i in importances:
    
    print(i, modelo.feature_importances_[i]*100, df.drop("price", axis = 1).columns[i])

1 38.09279606204697 accommodates
0 12.545764945972795 host_total_listings_count
13 11.729541644764907 Entire home/apt
12 10.292370479687131 city
8 5.704010021869435 availability_365
3 4.478624758998217 bedrooms
2 3.729493023377749 bathrooms_text
6 3.6959958674828375 minimum_nights
4 3.418956971512019 beds
11 2.814156796471453 neighbourhood_group_cleansed
10 1.1984557555074231 reviews_per_month
7 1.144304317263793 maximum_nights
5 0.6249129898512643 amenities
9 0.46869692362805143 number_of_reviews
14 0.06191944156594844 Private room

In [117]:
y_test_inv = y_scaler.inverse_transform([y_test]).flatten()
yhat_inv = y_scaler.inverse_transform([yhat]).flatten()


r2 = r2_score(y_test_inv, yhat_inv)
mse = mean_squared_error(y_test_inv, yhat_inv)

print(r2, mse)

0.6537545386397337 2199.59413428888

In [118]:
model = RandomForestRegressor(max_depth=16, max_features='sqrt', n_estimators=650, random_state = 42)
model.fit(X_train, y_train)

RandomForestRegressor(max_depth=16, max_features='sqrt', n_estimators=650,
                      random_state=42)

In [119]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [120]:
yhat = model.predict(X_test)

for i, j in zip(yhat[:5], y_test[:5]):
    print(f"Predicción:{i} \tValor real:{j}")

Predicción:0.181413556521411 	Valor real:0.19642857142857142
Predicción:0.21972238944840014 	Valor real:0.2397959183673469
Predicción:0.2532793722801895 	Valor real:0.2193877551020408
Predicción:0.1075069010385799 	Valor real:0.1173469387755102
Predicción:0.5349935948941689 	Valor real:0.3545918367346938

In [121]:
# Relative Absolute Error
RAE = np.sum(np.abs(np.subtract(y_test, yhat))) / np.sum(np.abs(np.subtract(y_test, np.mean(y_test))))

# Relative Square Error
RSE = np.sum(np.square(np.subtract(y_test, yhat))) / np.sum(np.square(np.subtract(y_test, np.mean(y_test))))

# Adjusted R**2
r2_ajustada = 1 - (1 - model.score(X_test, y_test))*(len(y_test) - 1)/(len(y_test) - X_test.shape[1] - 1)

In [122]:
print(f"MAE:\t {mean_absolute_error(yhat, y_test)}")
print(f"MSE:\t {mean_squared_error(yhat, y_test)}")
print(f"R**2:\t {r2_score(yhat, y_test)}")
print(f"RAE:\t {RAE}")
print(f"RSE:\t {RSE}")
print(f"Adjusted R**2:\t {r2_ajustada}")

MAE:	 0.0735754678383823
MSE:	 0.011754616061512572
R**2:	 0.5289799108047564
RAE:	 0.45664165077554203
RSE:	 0.28432962935691447
Adjusted R**2:	 0.7146209256528411

In [123]:
print(f"MSE:\t {mean_squared_error(yhat, y_test)}")

MSE:	 0.011754616061512572

In [124]:
print(f"MSE:\t {mean_squared_error(y_test, yhat)}")

MSE:	 0.011754616061512572

In [125]:
r2 = r2_score(y_test, yhat)
r2

0.7156703706430856

In [126]:
r2 = r2_score(yhat, y_test)
r2

0.5289799108047564

In [64]:
%%time

from sklearn.model_selection import GridSearchCV

# Modelo
model = RandomForestRegressor()

# Parametros a iterar
params = {"n_estimators" : [i for i in range(100, 1001, 50)],
          "max_depth"    : [8, 10, 12, 14, 16],
          "max_features" : ["log2", "sqrt"]}

# Metricas
scorers = {"r2", "neg_mean_squared_error"}

#GridSearchCV
grid_solver = GridSearchCV(estimator  = model, 
                           param_grid = params, 
                           scoring    = scorers,
                           cv         = 10,
                           refit      = "r2",
                           n_jobs     = -1, 
                           verbose    = 2)

# Resultados
model_result = grid_solver.fit(X_train, y_train)

Fitting 10 folds for each of 190 candidates, totalling 1900 fits

KeyboardInterrupt:

In [65]:
model_result.best_estimator_

NameError: name 'model_result' is not defined

In [ ]:
model_result.cv_results_["mean_test_r2"].max()

In [ ]:
model_result.cv_results_

In [ ]:
model_result.best_score_

In [47]:
# %%time

# from sklearn.model_selection import GridSearchCV

# # Modelo
# model = GradientBoostingRegressor()

# # Parametros a iterar
# params = {"n_estimators"  : [i for i in range(100, 1001, 50)],
#           "max_depth"     : [8, 10, 12, 14, 16],
#           "max_features"  : ["log2", "sqrt"],
#           "learning_rate" : [1 / (10**i) for i in range(1, 5)]}

# # Metricas
# scorers = {"r2", "neg_mean_squared_error"}

# #GridSearchCV
# grid_solver = GridSearchCV(estimator  = model, 
#                            param_grid = params, 
#                            scoring    = scorers,
#                            cv         = 10,
#                            refit      = "r2",
#                            n_jobs     = -1, 
#                            verbose    = 2)

# # Resultados
# model_result = grid_solver.fit(X_train, y_train)

In [48]:
# model_result.best_estimator_, model_result.best_score_

In [49]:
X_def = df.drop(["price"], axis = 1)
y_def = df["price"]

In [50]:
model = RandomForestRegressor(max_depth=16, max_features='sqrt', n_estimators=650, random_state = 42)
model.fit(X_def, y_def)

RandomForestRegressor(max_depth=16, max_features='sqrt', n_estimators=650,
                      random_state=42)

In [51]:
X_test.iloc[0, :].values

array([0.01741935, 0.        , 0.        , 0.        , 0.        ,
       0.28      , 0.        , 0.00789525, 1.        , 0.01337793,
       0.01376721, 0.86666667, 0.        , 1.        ])

In [52]:
import pickle


with open("model_rf.sav", "wb") as file:
    pickle.dump(model, file)

In [53]:
with open("model_gbr.sav", "rb") as file:
    model = pickle.load(file)

In [54]:
y_scaler.inverse_transform([model.predict([X_test.iloc[0, :].values])])

C:\Users\ignci\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

array([[83.45685412]])