In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

In [2]:
df_madrid = "madrid"
df_rome = "rome"
df_paris = "paris"
df_oslo = "oslo"
df_london = "london"
df_geneva = "geneva"
df_dublin = "dublin"
df_barcelona = "barcelona"
df_athens = "athens"
df_amsterdam = "amsterdam"

l_dataframes = [df_madrid, df_barcelona]

In [3]:
df_madrid["city"] = "madrid"
df_rome["city"] = "rome"
df_paris["city"] = "paris"
df_oslo["city"] = "oslo"
df_london["city"] = "london"
df_geneva["city"] = "geneva"
df_dublin["city"] = "dublin"
df_barcelona["city"] = "barcelona"
df_athens["city"] = "athens"
df_amsterdam["city"] = "amsterdam"

In [4]:
df_madrid

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
0,6369,https://www.airbnb.com/rooms/6369,20220911230855,2022-09-12,city scrape,"Rooftop terrace room , ensuite bathroom",Excellent connection with the AIRPORT and EXHI...,NaN,https://a0.muscache.com/pictures/683224/4cc318...,13660,...,4.82,4.85,NaN,f,1,0,1,0,0.65,madrid
1,21853,https://www.airbnb.com/rooms/21853,20220911230855,2022-09-12,city scrape,Bright and airy room,We have a quiet and sunny room with a good vie...,We live in a leafy neighbourhood with plenty o...,https://a0.muscache.com/pictures/68483181/87bc...,83531,...,4.21,4.67,NaN,f,2,0,2,0,0.34,madrid
2,24805,https://www.airbnb.com/rooms/24805,20220911230855,2022-09-12,city scrape,Gran Via Studio Madrid,"Studio located 50 meters from Gran Via, next t...","The area is next to the Gran Via, so people li...",https://a0.muscache.com/pictures/miso/Hosting-...,346366726,...,5.00,4.83,NaN,f,1,1,0,0,0.25,madrid
3,26825,https://www.airbnb.com/rooms/26825,20220911230855,2022-09-12,city scrape,Single Room whith private Bathroom,Nice and cozy roon for one person with a priva...,"Es un barrio muy tranquilo, en una zona de Mad...",https://a0.muscache.com/pictures/149358/218d5b...,114340,...,4.73,4.74,NaN,f,1,0,1,0,1.10,madrid
4,363476,https://www.airbnb.com/rooms/363476,20220911230855,2022-09-12,city scrape,PUERTA DEL SOL-QUIET DOWNTOWN,<b>The space</b><br />We want to welcome this ...,NaN,https://a0.muscache.com/pictures/4264879/ee070...,1836617,...,4.97,4.52,NaN,f,1,0,1,0,3.74,madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20676,50986852,https://www.airbnb.com/rooms/50986852,20220911230855,2022-09-12,city scrape,Precioso apartamento para 5 personas,Disfruta de la sencillez de este alojamiento t...,NaN,https://a0.muscache.com/pictures/b2da2e0f-3c5c...,17074819,...,4.00,5.00,NaN,f,5,2,3,0,0.59,madrid
20677,16486548,https://www.airbnb.com/rooms/16486548,20220911230855,2022-09-12,city scrape,"Amplio, luminoso y confortable",Espectacular piso compartido decoracion modern...,NaN,https://a0.muscache.com/pictures/3b89555a-530d...,30696902,...,4.00,4.00,NaN,f,8,2,6,0,0.36,madrid
20678,11961106,https://www.airbnb.com/rooms/11961106,20220911230855,2022-09-12,city scrape,Getafe Carlos III University,"The house is located in the center of Getafe ,...",NaN,https://a0.muscache.com/pictures/1367b7db-14d5...,63883696,...,4.65,4.82,NaN,f,1,0,1,0,0.24,madrid
20679,43692572,https://www.airbnb.com/rooms/43692572,20220911230855,2022-09-12,city scrape,Precioso Duplex con encanto en Pozuelo,Precioso Duplex de 2 habitaciones listo para r...,"Ubicado en la zona de la Avenida de Europa, en...",https://a0.muscache.com/pictures/61131c33-f557...,85797262,...,4.83,4.67,NaN,f,2,1,1,0,0.44,madrid
20680,50808000,https://www.airbnb.com/rooms/50808000,20220911230855,2022-09-12,city scrape,Precioso apartamento en Alcorcón,Relájate y desconecta en este alojamiento tran...,NaN,https://a0.muscache.com/pictures/8031c073-685e...,409085640,...,4.50,5.00,NaN,t,1,1,0,0,0.14,madrid

In [5]:
for i in l_dataframes:
    i.drop("source", axis = 1, inplace = True)

In [6]:
for i in l_dataframes:
    print(i.shape)

(20681, 75)
(16920, 75)

In [7]:
df = pd.concat(l_dataframes)
df

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
0,6369,https://www.airbnb.com/rooms/6369,20220911230855,2022-09-12,"Rooftop terrace room , ensuite bathroom",Excellent connection with the AIRPORT and EXHI...,NaN,https://a0.muscache.com/pictures/683224/4cc318...,13660,https://www.airbnb.com/users/show/13660,...,4.82,4.85,NaN,f,1,0,1,0,0.65,madrid
1,21853,https://www.airbnb.com/rooms/21853,20220911230855,2022-09-12,Bright and airy room,We have a quiet and sunny room with a good vie...,We live in a leafy neighbourhood with plenty o...,https://a0.muscache.com/pictures/68483181/87bc...,83531,https://www.airbnb.com/users/show/83531,...,4.21,4.67,NaN,f,2,0,2,0,0.34,madrid
2,24805,https://www.airbnb.com/rooms/24805,20220911230855,2022-09-12,Gran Via Studio Madrid,"Studio located 50 meters from Gran Via, next t...","The area is next to the Gran Via, so people li...",https://a0.muscache.com/pictures/miso/Hosting-...,346366726,https://www.airbnb.com/users/show/346366726,...,5.00,4.83,NaN,f,1,1,0,0,0.25,madrid
3,26825,https://www.airbnb.com/rooms/26825,20220911230855,2022-09-12,Single Room whith private Bathroom,Nice and cozy roon for one person with a priva...,"Es un barrio muy tranquilo, en una zona de Mad...",https://a0.muscache.com/pictures/149358/218d5b...,114340,https://www.airbnb.com/users/show/114340,...,4.73,4.74,NaN,f,1,0,1,0,1.10,madrid
4,363476,https://www.airbnb.com/rooms/363476,20220911230855,2022-09-12,PUERTA DEL SOL-QUIET DOWNTOWN,<b>The space</b><br />We want to welcome this ...,NaN,https://a0.muscache.com/pictures/4264879/ee070...,1836617,https://www.airbnb.com/users/show/1836617,...,4.97,4.52,NaN,f,1,0,1,0,3.74,madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16915,26383234,https://www.airbnb.com/rooms/26383234,20220910194401,2022-09-11,LOVELY PRIVATE ROOM FOR 6 GUESTS ENSUITE BATHROOM,"PRIVATE ROOM FOR 6 GUESTS, TOTAL PRICE FOR 6 G...",COLLBLANC QUARTER next to BARCELONA CAMP NOU S...,https://a0.muscache.com/pictures/miso/Hosting-...,198281707,https://www.airbnb.com/users/show/198281707,...,4.37,4.10,HUTB-172880,f,12,0,12,0,0.59,barcelona
16916,26383143,https://www.airbnb.com/rooms/26383143,20220910194401,2022-09-11,LOVELY PRIVATE ROOM FOR 6 GUESTS ENSUITE BATHROOM,"PRIVATE ROOM FOR 6 GUESTS, TOTAL PRICE FOR 6 G...",COLLBLANC QUARTER next to BARCELONA CAMP NOU S...,https://a0.muscache.com/pictures/miso/Hosting-...,198281707,https://www.airbnb.com/users/show/198281707,...,4.00,4.00,HUTB-172880,f,12,0,12,0,0.05,barcelona
16917,26384664,https://www.airbnb.com/rooms/26384664,20220910194401,2022-09-11,HABITACION PRIVADA DE 6 CAMAS CON TERRAZA PRIVADA,PRIVATE ROOM FOR 6 PERSONS WITH PRIVATE TERRAC...,COLLBLANC QUARTER next to BARCELONA CAMP NOU S...,https://a0.muscache.com/pictures/miso/Hosting-...,198281707,https://www.airbnb.com/users/show/198281707,...,4.31,4.31,HUTB-172880,f,12,0,12,0,0.33,barcelona
16918,18220085,https://www.airbnb.com/rooms/18220085,20220910194401,2022-09-11,"Chillout house, with garden and pool for family","Our house, build in 1958 and totally renewed i...",Esplugues de Llobregat / Sant Just is a peacef...,https://a0.muscache.com/pictures/ee758054-4870...,10030977,https://www.airbnb.com/users/show/10030977,...,4.64,4.64,HUTB-017296,f,1,1,0,0,0.19,barcelona
16919,5122846,https://www.airbnb.com/rooms/5122846,20220910194401,2022-09-11,"3 Peaceful, double bedrooms in musical family ...",Cozy bedroom with own patio and bathroom in la...,NaN,https://a0.muscache.com/pictures/7636007f-a685...,1145453,https://www.airbnb.com/users/show/1145453,...,4.40,5.00,NaN,f,3,0,3,0,0.06,barcelona

In [8]:
# df[["reviews_per_month"]]
# df["reviews_per_month"] = df["reviews_per_month"].fillna(df["reviews_per_month"].mean())

In [9]:
# df["reviews_per_month"]

# from sklearn.impute import KNNImputer

# imputer = KNNImputer(n_neighbors = 3)

# df_num_imp = imputer.fit_transform(df[["reviews_per_month"]])

# df["reviews_per_month"] = df_num_imp

In [10]:
columns_drop = ["listing_url", "scrape_id", "last_scraped", "description", "picture_url", "host_url", "host_about",
                "host_location", "name", "neighborhood_overview", "host_since", "host_thumbnail_url", "host_picture_url",
                "host_neighbourhood", "host_listings_count", "host_has_profile_pic", "bathrooms", "calendar_updated",
                "has_availability", "calendar_last_scraped", "number_of_reviews_ltm", "number_of_reviews_l30d",
                "first_review", "last_review", "review_scores_rating", "review_scores_accuracy", "review_scores_cleanliness",
                "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value",
                "license", "calculated_host_listings_count_entire_homes", "calculated_host_listings_count_private_rooms",
                "calculated_host_listings_count_shared_rooms", "neighbourhood", "host_name", "calculated_host_listings_count"]

columns_maybe_drop = ["host_response_time", "host_response_rate", "host_acceptance_rate", "host_is_superhost",
                      "host_identity_verified", "minimum_minimum_nights", "minimum_minimum_nights", "maximum_minimum_nights",
                      "minimum_maximum_nights", "maximum_maximum_nights", "minimum_nights_avg_ntm", "maximum_nights_avg_ntm",
                      "availability_30", "availability_60", "availability_90"]

In [11]:
df.drop(columns = columns_drop + columns_maybe_drop, axis = 1, inplace = True)

In [12]:
df.isna().sum()/df.shape[0]*100

id                               0.000000
host_id                          0.000000
host_total_listings_count        0.013298
host_verifications               0.000000
neighbourhood_cleansed           0.000000
neighbourhood_group_cleansed     0.000000
latitude                         0.000000
longitude                        0.000000
property_type                    0.000000
room_type                        0.000000
accommodates                     0.000000
bathrooms_text                   0.093083
bedrooms                         5.385495
beds                             1.726018
amenities                        0.000000
price                            0.000000
minimum_nights                   0.000000
maximum_nights                   0.000000
availability_365                 0.000000
number_of_reviews                0.000000
instant_bookable                 0.000000
reviews_per_month               21.478152
city                             0.000000
dtype: float64

In [13]:
# host_verifications: número de elementos en la lista
df["host_verifications"] = df["host_verifications"].apply(lambda x : len(json.loads((x.replace("'", '"')))) if x != "None" else np.nan)

In [14]:
# bathrooms_text: limpieza de columna

df["bathrooms_text"] = df["bathrooms_text"].apply(lambda x : x.split(" ")[0] if (type(x) == str) and ("bath" in x) else np.nan)

bath_map = {"Private" : 1, "Shared" : 0.5, "Half-bath" : 0.5}

df["bathrooms_text"] = df["bathrooms_text"].apply(lambda x : bath_map[x] if x in bath_map.keys() else float(x))

In [15]:
import json
l_amenities_cleaned = list()
for i in df["amenities"]:
    
    l_amenities_cleaned.append(json.loads(i))
    
# More relevant amenities, to see why check EDA


l_amenities_valuables = ['Long term stays allowed','Cooking basics','Dishes and silverware','Essentials','Coffee maker','Hair dryer','Microwave','Refrigerator','Heating','Air conditioning']
                         
df_amenities_valuables = pd.DataFrame()

for j in l_amenities_valuables:
    
    df[j] = [1 if j in i else 0 for i in l_amenities_cleaned]
    
df.drop("amenities", axis =1, inplace=True)

In [16]:
df

,id,host_id,host_total_listings_count,host_verifications,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,...,Long term stays allowed,Cooking basics,Dishes and silverware,Essentials,Coffee maker,Hair dryer,Microwave,Refrigerator,Heating,Air conditioning
0,6369,13660,1.0,2.0,Hispanoamérica,Chamartín,40.45724,-3.67688,Private room in rental unit,Private room,...,1,1,1,1,1,1,1,1,0,0
1,21853,83531,2.0,2.0,Cármenes,Latina,40.40381,-3.74130,Private room in rental unit,Private room,...,1,1,1,1,1,1,1,1,1,1
2,24805,346366726,1.0,2.0,Universidad,Centro,40.42183,-3.70529,Entire rental unit,Entire home/apt,...,1,1,1,1,1,1,1,1,1,0
3,26825,114340,4.0,2.0,Legazpi,Arganzuela,40.38975,-3.69018,Private room in home,Private room,...,1,0,1,1,0,1,0,1,1,0
4,363476,1836617,1.0,3.0,Sol,Centro,40.41676,-3.70682,Private room in rental unit,Private room,...,1,0,1,1,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16915,26383234,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37377,2.11757,Private room in hostel,Private room,...,0,1,1,1,1,1,1,1,1,1
16916,26383143,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37377,2.11757,Private room in hostel,Private room,...,0,1,1,1,1,1,1,1,1,1
16917,26384664,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37411,2.11852,Private room in hostel,Private room,...,0,1,1,1,1,1,1,1,1,1
16918,18220085,10030977,2.0,3.0,Pedralbes,Les Corts,41.38844,2.08789,Entire home,Entire home/apt,...,1,1,1,1,1,1,1,1,1,0
16919,5122846,1145453,6.0,3.0,"Vallvidrera, el Tibidabo i les Planes",Sarrià-Sant Gervasi,41.38510,2.07642,Private room in villa,Private room,...,0,1,1,1,1,1,1,0,1,0

In [17]:
# # amenities: número de elementos en la lista

# list_amenities = list()

# for num, x in enumerate(df["amenities"].values):
#     try:
#         list_amenities.append(len(json.loads((x.replace("'", '"')))))
        
#     except:
#         list_amenities.append(len(x.replace("'", '"').replace("\\", "")))
        
        
# df["amenities"] = list_amenities

In [18]:
# Quito esta columna por la cantidad de NaN's, pero creo que si estuviera el modelo daría mejores resultados
# Se pueden llenar con KNNImputer

# df.drop("reviews_per_month", axis = 1, inplace = True)
# df.dropna(inplace = True)

In [19]:
df

,id,host_id,host_total_listings_count,host_verifications,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,...,Long term stays allowed,Cooking basics,Dishes and silverware,Essentials,Coffee maker,Hair dryer,Microwave,Refrigerator,Heating,Air conditioning
0,6369,13660,1.0,2.0,Hispanoamérica,Chamartín,40.45724,-3.67688,Private room in rental unit,Private room,...,1,1,1,1,1,1,1,1,0,0
1,21853,83531,2.0,2.0,Cármenes,Latina,40.40381,-3.74130,Private room in rental unit,Private room,...,1,1,1,1,1,1,1,1,1,1
2,24805,346366726,1.0,2.0,Universidad,Centro,40.42183,-3.70529,Entire rental unit,Entire home/apt,...,1,1,1,1,1,1,1,1,1,0
3,26825,114340,4.0,2.0,Legazpi,Arganzuela,40.38975,-3.69018,Private room in home,Private room,...,1,0,1,1,0,1,0,1,1,0
4,363476,1836617,1.0,3.0,Sol,Centro,40.41676,-3.70682,Private room in rental unit,Private room,...,1,0,1,1,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16915,26383234,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37377,2.11757,Private room in hostel,Private room,...,0,1,1,1,1,1,1,1,1,1
16916,26383143,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37377,2.11757,Private room in hostel,Private room,...,0,1,1,1,1,1,1,1,1,1
16917,26384664,198281707,12.0,2.0,la Maternitat i Sant Ramon,Les Corts,41.37411,2.11852,Private room in hostel,Private room,...,0,1,1,1,1,1,1,1,1,1
16918,18220085,10030977,2.0,3.0,Pedralbes,Les Corts,41.38844,2.08789,Entire home,Entire home/apt,...,1,1,1,1,1,1,1,1,1,0
16919,5122846,1145453,6.0,3.0,"Vallvidrera, el Tibidabo i les Planes",Sarrià-Sant Gervasi,41.38510,2.07642,Private room in villa,Private room,...,0,1,1,1,1,1,1,0,1,0

In [20]:
df_num = df._get_numeric_data()
df_num

,id,host_id,host_total_listings_count,host_verifications,latitude,longitude,accommodates,bathrooms_text,bedrooms,beds,...,Long term stays allowed,Cooking basics,Dishes and silverware,Essentials,Coffee maker,Hair dryer,Microwave,Refrigerator,Heating,Air conditioning
0,6369,13660,1.0,2.0,40.45724,-3.67688,2,1.0,1.0,1.0,...,1,1,1,1,1,1,1,1,0,0
1,21853,83531,2.0,2.0,40.40381,-3.74130,1,1.0,1.0,1.0,...,1,1,1,1,1,1,1,1,1,1
2,24805,346366726,1.0,2.0,40.42183,-3.70529,3,1.0,NaN,1.0,...,1,1,1,1,1,1,1,1,1,0
3,26825,114340,4.0,2.0,40.38975,-3.69018,1,1.0,1.0,1.0,...,1,0,1,1,0,1,0,1,1,0
4,363476,1836617,1.0,3.0,40.41676,-3.70682,2,1.5,1.0,1.0,...,1,0,1,1,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16915,26383234,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,0,1,1,1,1,1,1,1,1,1
16916,26383143,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,0,1,1,1,1,1,1,1,1,1
16917,26384664,198281707,12.0,2.0,41.37411,2.11852,6,1.5,1.0,6.0,...,0,1,1,1,1,1,1,1,1,1
16918,18220085,10030977,2.0,3.0,41.38844,2.08789,5,2.0,4.0,5.0,...,1,1,1,1,1,1,1,1,1,0
16919,5122846,1145453,6.0,3.0,41.38510,2.07642,1,1.0,1.0,1.0,...,0,1,1,1,1,1,1,0,1,0

In [21]:
# Agrego la columna id para después hacer pd.merge()

df_cat = df.drop(df_num.columns, axis = 1)
df_cat = pd.concat([df_cat, df_num[["id"]]], axis = 1)
df_cat

,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,price,instant_bookable,city,id
0,Hispanoamérica,Chamartín,Private room in rental unit,Private room,$77.00,f,madrid,6369
1,Cármenes,Latina,Private room in rental unit,Private room,$31.00,f,madrid,21853
2,Universidad,Centro,Entire rental unit,Entire home/apt,$92.00,f,madrid,24805
3,Legazpi,Arganzuela,Private room in home,Private room,$26.00,f,madrid,26825
4,Sol,Centro,Private room in rental unit,Private room,$49.00,f,madrid,363476
...,...,...,...,...,...,...,...,...
16915,la Maternitat i Sant Ramon,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26383234
16916,la Maternitat i Sant Ramon,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26383143
16917,la Maternitat i Sant Ramon,Les Corts,Private room in hostel,Private room,"$5,000.00",f,barcelona,26384664
16918,Pedralbes,Les Corts,Entire home,Entire home/apt,$250.00,f,barcelona,18220085
16919,"Vallvidrera, el Tibidabo i les Planes",Sarrià-Sant Gervasi,Private room in villa,Private room,$33.00,f,barcelona,5122846

In [22]:
# Decido quedarme solo con "neighbourhood_group_cleansed"

df_cat.drop(["neighbourhood_group_cleansed"], axis = 1, inplace = True)

df_cat

,neighbourhood_cleansed,property_type,room_type,price,instant_bookable,city,id
0,Hispanoamérica,Private room in rental unit,Private room,$77.00,f,madrid,6369
1,Cármenes,Private room in rental unit,Private room,$31.00,f,madrid,21853
2,Universidad,Entire rental unit,Entire home/apt,$92.00,f,madrid,24805
3,Legazpi,Private room in home,Private room,$26.00,f,madrid,26825
4,Sol,Private room in rental unit,Private room,$49.00,f,madrid,363476
...,...,...,...,...,...,...,...
16915,la Maternitat i Sant Ramon,Private room in hostel,Private room,"$5,000.00",f,barcelona,26383234
16916,la Maternitat i Sant Ramon,Private room in hostel,Private room,"$5,000.00",f,barcelona,26383143
16917,la Maternitat i Sant Ramon,Private room in hostel,Private room,"$5,000.00",f,barcelona,26384664
16918,Pedralbes,Entire home,Entire home/apt,$250.00,f,barcelona,18220085
16919,"Vallvidrera, el Tibidabo i les Planes",Private room in villa,Private room,$33.00,f,barcelona,5122846

In [23]:
# price: limpieza de columna
df_cat["price"] = df_cat["price"].apply(lambda x : float(x.strip("$").replace(",", "")))

In [24]:
# instant_bookable: transformar a 0 y 1
df_cat["instant_bookable"] = df_cat["instant_bookable"].apply(lambda x : 0 if x == "f" else 1)

In [25]:
# room_type: eliminar "Hotel room" y transformar a dummies

df_cat = df_cat[df_cat["room_type"] != "Hotel room"]

df_cat = pd.concat([df_cat, pd.get_dummies(data = df_cat["room_type"])], axis = 1).drop("room_type", axis = 1)

In [26]:
df_cat

,neighbourhood_cleansed,property_type,price,instant_bookable,city,id,Entire home/apt,Private room,Shared room
0,Hispanoamérica,Private room in rental unit,77.0,0,madrid,6369,0,1,0
1,Cármenes,Private room in rental unit,31.0,0,madrid,21853,0,1,0
2,Universidad,Entire rental unit,92.0,0,madrid,24805,1,0,0
3,Legazpi,Private room in home,26.0,0,madrid,26825,0,1,0
4,Sol,Private room in rental unit,49.0,0,madrid,363476,0,1,0
...,...,...,...,...,...,...,...,...,...
16915,la Maternitat i Sant Ramon,Private room in hostel,5000.0,0,barcelona,26383234,0,1,0
16916,la Maternitat i Sant Ramon,Private room in hostel,5000.0,0,barcelona,26383143,0,1,0
16917,la Maternitat i Sant Ramon,Private room in hostel,5000.0,0,barcelona,26384664,0,1,0
16918,Pedralbes,Entire home,250.0,0,barcelona,18220085,1,0,0
16919,"Vallvidrera, el Tibidabo i les Planes",Private room in villa,33.0,0,barcelona,5122846,0,1,0

In [27]:
# property_type está representada port la columnas dummies de room_type

df_cat.drop("property_type", axis = 1, inplace = True)

In [28]:
# Uso el LabelEncoder para transformarlo a números sin ningún tipo de relación u orden

from sklearn.preprocessing import LabelEncoder

neighbourhood_group_encoder = LabelEncoder()
df_cat["neighbourhood_cleansed"] = neighbourhood_group_encoder.fit_transform(df_cat["neighbourhood_cleansed"])

In [29]:
from sklearn.preprocessing import LabelEncoder

neighbourhood_group_encoder = LabelEncoder()
df_cat["city"] = neighbourhood_group_encoder.fit_transform(df_cat["city"])

In [30]:
df = pd.merge(left = df_num, right = df_cat, on = "id")

df

,id,host_id,host_total_listings_count,host_verifications,latitude,longitude,accommodates,bathrooms_text,bedrooms,beds,...,Refrigerator,Heating,Air conditioning,neighbourhood_cleansed,price,instant_bookable,city,Entire home/apt,Private room,Shared room
0,6369,13660,1.0,2.0,40.45724,-3.67688,2,1.0,1.0,1.0,...,1,0,0,66,77.0,0,1,0,1,0
1,21853,83531,2.0,2.0,40.40381,-3.74130,1,1.0,1.0,1.0,...,1,1,1,49,31.0,0,1,0,1,0
2,24805,346366726,1.0,2.0,40.42183,-3.70529,3,1.0,NaN,1.0,...,1,1,0,141,92.0,0,1,1,0,0
3,26825,114340,4.0,2.0,40.38975,-3.69018,1,1.0,1.0,1.0,...,1,1,0,75,26.0,0,1,0,1,0
4,363476,1836617,1.0,3.0,40.41676,-3.70682,2,1.5,1.0,1.0,...,1,1,0,137,49.0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37293,26383234,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,1,1,1,185,5000.0,0,0,0,1,0
37294,26383143,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,1,1,1,185,5000.0,0,0,0,1,0
37295,26384664,198281707,12.0,2.0,41.37411,2.11852,6,1.5,1.0,6.0,...,1,1,1,185,5000.0,0,0,0,1,0
37296,18220085,10030977,2.0,3.0,41.38844,2.08789,5,2.0,4.0,5.0,...,1,1,0,99,250.0,0,0,1,0,0
37297,5122846,1145453,6.0,3.0,41.38510,2.07642,1,1.0,1.0,1.0,...,0,1,0,149,33.0,0,0,0,1,0

In [31]:
df.dropna(inplace = True)

### Outliers

In [32]:
df

,id,host_id,host_total_listings_count,host_verifications,latitude,longitude,accommodates,bathrooms_text,bedrooms,beds,...,Refrigerator,Heating,Air conditioning,neighbourhood_cleansed,price,instant_bookable,city,Entire home/apt,Private room,Shared room
0,6369,13660,1.0,2.0,40.45724,-3.67688,2,1.0,1.0,1.0,...,1,0,0,66,77.0,0,1,0,1,0
1,21853,83531,2.0,2.0,40.40381,-3.74130,1,1.0,1.0,1.0,...,1,1,1,49,31.0,0,1,0,1,0
3,26825,114340,4.0,2.0,40.38975,-3.69018,1,1.0,1.0,1.0,...,1,1,0,75,26.0,0,1,0,1,0
4,363476,1836617,1.0,3.0,40.41676,-3.70682,2,1.5,1.0,1.0,...,1,1,0,137,49.0,0,1,0,1,0
5,30320,130907,6.0,2.0,40.41476,-3.70418,2,1.0,1.0,2.0,...,0,1,1,137,120.0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37293,26383234,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,1,1,1,185,5000.0,0,0,0,1,0
37294,26383143,198281707,12.0,2.0,41.37377,2.11757,6,1.5,1.0,6.0,...,1,1,1,185,5000.0,0,0,0,1,0
37295,26384664,198281707,12.0,2.0,41.37411,2.11852,6,1.5,1.0,6.0,...,1,1,1,185,5000.0,0,0,0,1,0
37296,18220085,10030977,2.0,3.0,41.38844,2.08789,5,2.0,4.0,5.0,...,1,1,0,99,250.0,0,0,1,0,0
37297,5122846,1145453,6.0,3.0,41.38510,2.07642,1,1.0,1.0,1.0,...,0,1,0,149,33.0,0,0,0,1,0

In [33]:
df["bathrooms_text"] = df["bathrooms_text"].apply(lambda x : np.ceil(x))

In [34]:
# Eliminé outliers solo viendo las gráficas
# Elimino alrededor de 4000 filas (muchísimo)

df = df[df["accommodates"] <= 8]
df = df[df["bathrooms_text"].between(1, 2)]
df = df[df["bedrooms"] <= 4]
df = df[df["beds"].between(1, 5)]
#df = df[df["amenities"] <= 50]
df = df[df["minimum_nights"] <= 30]
df = df[df["number_of_reviews"] <= 300]
df = df[df["reviews_per_month"] <= 8]
df = df[df["price"] <= 400]
# df = df[df["host_total_listings_count"] <= 40]

In [35]:
df

,id,host_id,host_total_listings_count,host_verifications,latitude,longitude,accommodates,bathrooms_text,bedrooms,beds,...,Refrigerator,Heating,Air conditioning,neighbourhood_cleansed,price,instant_bookable,city,Entire home/apt,Private room,Shared room
0,6369,13660,1.0,2.0,40.45724,-3.67688,2,1.0,1.0,1.0,...,1,0,0,66,77.0,0,1,0,1,0
1,21853,83531,2.0,2.0,40.40381,-3.74130,1,1.0,1.0,1.0,...,1,1,1,49,31.0,0,1,0,1,0
3,26825,114340,4.0,2.0,40.38975,-3.69018,1,1.0,1.0,1.0,...,1,1,0,75,26.0,0,1,0,1,0
5,30320,130907,6.0,2.0,40.41476,-3.70418,2,1.0,1.0,2.0,...,0,1,1,137,120.0,0,1,1,0,0
6,30478,130502,19.0,2.0,40.40949,-3.70477,1,1.0,1.0,1.0,...,0,1,0,56,20.0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37286,49721277,401005122,2.0,2.0,41.44968,2.07538,3,2.0,2.0,2.0,...,0,1,1,149,109.0,1,0,1,0,0
37288,38999916,298840255,3.0,2.0,41.41577,2.22739,4,1.0,2.0,2.0,...,1,1,0,159,146.0,1,0,1,0,0
37289,53824883,10380563,83.0,2.0,41.41490,2.22120,6,1.0,3.0,4.0,...,1,0,1,159,231.0,1,0,1,0,0
37296,18220085,10030977,2.0,3.0,41.38844,2.08789,5,2.0,4.0,5.0,...,1,1,0,99,250.0,0,0,1,0,0
37297,5122846,1145453,6.0,3.0,41.38510,2.07642,1,1.0,1.0,1.0,...,0,1,0,149,33.0,0,0,0,1,0

In [36]:
# Elimono "Shared room" por el desbalance, casí no aparace en comparación a los otros

df.drop("Shared room", axis = 1, inplace = True)

In [37]:
df

,id,host_id,host_total_listings_count,host_verifications,latitude,longitude,accommodates,bathrooms_text,bedrooms,beds,...,Microwave,Refrigerator,Heating,Air conditioning,neighbourhood_cleansed,price,instant_bookable,city,Entire home/apt,Private room
0,6369,13660,1.0,2.0,40.45724,-3.67688,2,1.0,1.0,1.0,...,1,1,0,0,66,77.0,0,1,0,1
1,21853,83531,2.0,2.0,40.40381,-3.74130,1,1.0,1.0,1.0,...,1,1,1,1,49,31.0,0,1,0,1
3,26825,114340,4.0,2.0,40.38975,-3.69018,1,1.0,1.0,1.0,...,0,1,1,0,75,26.0,0,1,0,1
5,30320,130907,6.0,2.0,40.41476,-3.70418,2,1.0,1.0,2.0,...,0,0,1,1,137,120.0,0,1,1,0
6,30478,130502,19.0,2.0,40.40949,-3.70477,1,1.0,1.0,1.0,...,0,0,1,0,56,20.0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37286,49721277,401005122,2.0,2.0,41.44968,2.07538,3,2.0,2.0,2.0,...,0,0,1,1,149,109.0,1,0,1,0
37288,38999916,298840255,3.0,2.0,41.41577,2.22739,4,1.0,2.0,2.0,...,1,1,1,0,159,146.0,1,0,1,0
37289,53824883,10380563,83.0,2.0,41.41490,2.22120,6,1.0,3.0,4.0,...,1,1,0,1,159,231.0,1,0,1,0
37296,18220085,10030977,2.0,3.0,41.38844,2.08789,5,2.0,4.0,5.0,...,1,1,1,0,99,250.0,0,0,1,0
37297,5122846,1145453,6.0,3.0,41.38510,2.07642,1,1.0,1.0,1.0,...,1,0,1,0,149,33.0,0,0,0,1

### Normalizar

In [38]:
from sklearn.preprocessing import MinMaxScaler

x_scaler = MinMaxScaler()
df[df.drop("price", axis = 1).columns] = x_scaler.fit_transform(df[df.drop("price", axis = 1).columns])

y_scaler = MinMaxScaler()
df["price"] = y_scaler.fit_transform(df[["price"]]).flatten()

In [39]:
df.drop(["host_id", "id", "latitude", "longitude"], axis = 1, inplace = True)

In [40]:
df.drop(["instant_bookable", "host_verifications"], axis = 1, inplace = True)

In [41]:
df.dropna(inplace=True)

In [42]:
df.columns

Index(['host_total_listings_count', 'accommodates', 'bathrooms_text',
       'bedrooms', 'beds', 'minimum_nights', 'maximum_nights',
       'availability_365', 'number_of_reviews', 'reviews_per_month',
       'Long term stays allowed', 'Cooking basics', 'Dishes and silverware',
       'Essentials', 'Coffee maker', 'Hair dryer', 'Microwave', 'Refrigerator',
       'Heating', 'Air conditioning', 'neighbourhood_cleansed', 'price',
       'city', 'Entire home/apt', 'Private room'],
      dtype='object')

In [43]:
X = df.drop(["price"], axis = 1)
y = df["price"]

print(X.shape, y.shape)

(20886, 24) (20886,)

### Train, Test

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print(f"X_train: {X_train.shape} | y_train: {y_train.shape}")
print(f"X_test: {X_test.shape} | y_test: {y_test.shape}")

X_train: (16708, 24) | y_train: (16708,)
X_test: (4178, 24) | y_test: (4178,)

### Modelos y Métricas

In [45]:
# Modelos
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor

# Métricas
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [46]:
%%time

modelos = [LinearRegression(), KNeighborsRegressor(), DecisionTreeRegressor(),
           RandomForestRegressor(), SVR(), AdaBoostRegressor(), GradientBoostingRegressor()]

metricas = list() 

for model in modelos:
    
    # fit
    model.fit(X_train, y_train)
    
    # predict
    yhat = model.predict(X_test)
    
    # metrics
    r2 = r2_score(y_test, yhat)
    mse = mean_squared_error(y_test, yhat)
    
    metricas.append([str(model), r2, mse, model])
    
df_metricas = pd.DataFrame(data = metricas, columns = ["model_name", "r2", "mse", "model"])

df_metricas.sort_values(by = "r2", ascending = False)

CPU times: user 19.8 s, sys: 1.25 s, total: 21 s
Wall time: 19.1 s

,model_name,r2,mse,model
3,RandomForestRegressor(),0.717131,0.011780,"(DecisionTreeRegressor(max_features='auto', ra..."
6,GradientBoostingRegressor(),0.652795,0.014459,([DecisionTreeRegressor(criterion='friedman_ms...
4,SVR(),0.636418,0.015141,SVR()
1,KNeighborsRegressor(),0.586060,0.017238,KNeighborsRegressor()
0,LinearRegression(),0.566661,0.018046,LinearRegression()
5,AdaBoostRegressor(),0.465711,0.022250,"(DecisionTreeRegressor(max_depth=3, random_sta..."
2,DecisionTreeRegressor(),0.442467,0.023218,DecisionTreeRegressor()

In [47]:
modelo = df_metricas["model"][3]

modelo

RandomForestRegressor()

In [48]:
importances = np.argsort(modelo.feature_importances_)[::-1]

for i in importances:
    
    print(i, modelo.feature_importances_[i]*100, df.drop("price", axis = 1).columns[i])

1 23.893908666370415 accommodates
22 13.22132749901536 Entire home/apt
0 10.283202546555678 host_total_listings_count
21 8.791870308860748 city
7 8.257009725768697 availability_365
9 5.611776800667848 reviews_per_month
20 5.294316986382815 neighbourhood_cleansed
8 4.238692464262561 number_of_reviews
5 4.1714880663790215 minimum_nights
2 3.814821262424034 bathrooms_text
6 2.8247103681349395 maximum_nights
3 2.0252371934246107 bedrooms
4 1.415755926473196 beds
19 1.2481681105829943 Air conditioning
12 0.8948676335272943 Dishes and silverware
18 0.6046164052205437 Heating
11 0.59823095327901 Cooking basics
14 0.586468474116158 Coffee maker
15 0.5626261548431006 Hair dryer
13 0.49423729400342364 Essentials
16 0.49349152405992813 Microwave
17 0.41036613020037827 Refrigerator
10 0.14868750822040674 Long term stays allowed
23 0.11412199722683676 Private room

In [49]:
modelo = df_metricas["model"][6]

importances = np.argsort(modelo.feature_importances_)[::-1]

for i in importances:
    
    print(i, modelo.feature_importances_[i]*100, df.drop("price", axis = 1).columns[i])

1 34.91979695446613 accommodates
22 14.191603188959265 Entire home/apt
0 11.103260071062904 host_total_listings_count
21 9.457963441619196 city
7 6.151834571295532 availability_365
3 5.1433558505204315 bedrooms
2 4.0918334083600385 bathrooms_text
20 3.5422921492787105 neighbourhood_cleansed
5 3.062627037995528 minimum_nights
4 2.3427250974740357 beds
19 2.2920283554829775 Air conditioning
15 1.1037350248775326 Hair dryer
9 0.6692552857208555 reviews_per_month
8 0.510377064185594 number_of_reviews
14 0.38254187711729853 Coffee maker
6 0.3592730705597368 maximum_nights
11 0.2630562907713369 Cooking basics
13 0.15210203972165878 Essentials
12 0.11873374266977649 Dishes and silverware
23 0.06638638547282003 Private room
18 0.044077878790419744 Heating
16 0.027210643612093216 Microwave
10 0.003930569986128346 Long term stays allowed
17 0.0 Refrigerator

In [50]:
y_test_inv = y_scaler.inverse_transform([y_test]).flatten()
yhat_inv = y_scaler.inverse_transform([yhat]).flatten()


r2 = r2_score(y_test_inv, yhat_inv)
mse = mean_squared_error(y_test_inv, yhat_inv)

print(r2, mse)

0.6527948226137598 2221.8265438156336

In [51]:
model = RandomForestRegressor(max_depth=16, max_features='sqrt', n_estimators=650, random_state = 42)
model.fit(X_train, y_train)

RandomForestRegressor(max_depth=16, max_features='sqrt', n_estimators=650,
                      random_state=42)

In [52]:
yhat = model.predict(X_test)

for i, j in zip(yhat_inv[:5], y_test_inv[:5]):
    print(f"Predicción:{i} \tValor real:{j}")

Predicción:168.491339059185 	Valor real:185.0
Predicción:157.25119913842423 	Valor real:149.0
Predicción:33.28196014401058 	Valor real:26.0
Predicción:49.99794862279712 	Valor real:59.00000000000001
Predicción:38.5685820234401 	Valor real:35.0

In [53]:
r2 = r2_score(y_test, yhat)
r2

0.7122424435056993

In [54]:
# %%time

# from sklearn.model_selection import GridSearchCV

# # Modelo
# model = RandomForestRegressor()

# # Parametros a iterar
# params = {"n_estimators" : [i for i in range(100, 1001, 50)],
#           "max_depth"    : [8, 10, 12, 14, 16],
#           "max_features" : ["log2", "sqrt"]}

# # Metricas
# scorers = {"r2", "neg_mean_squared_error"}

# #GridSearchCV
# grid_solver = GridSearchCV(estimator  = model, 
#                            param_grid = params, 
#                            scoring    = scorers,
#                            cv         = 10,
#                            refit      = "r2",
#                            n_jobs     = -1, 
#                            verbose    = 2)

# # Resultados
# model_result = grid_solver.fit(X_train, y_train)

In [55]:
model_result.best_estimator_

NameError: name 'model_result' is not defined

In [ ]:
model_result.cv_results_["mean_test_r2"].max()

In [ ]:
model_result.cv_results_

In [ ]:
model_result.best_score_

In [ ]:
# %%time

# from sklearn.model_selection import GridSearchCV

# # Modelo
# model = GradientBoostingRegressor()

# # Parametros a iterar
# params = {"n_estimators"  : [i for i in range(100, 1001, 50)],
#           "max_depth"     : [8, 10, 12, 14, 16],
#           "max_features"  : ["log2", "sqrt"],
#           "learning_rate" : [1 / (10**i) for i in range(1, 5)]}

# # Metricas
# scorers = {"r2", "neg_mean_squared_error"}

# #GridSearchCV
# grid_solver = GridSearchCV(estimator  = model, 
#                            param_grid = params, 
#                            scoring    = scorers,
#                            cv         = 10,
#                            refit      = "r2",
#                            n_jobs     = -1, 
#                            verbose    = 2)

# # Resultados
# model_result = grid_solver.fit(X_train, y_train)

In [ ]:
# model_result.best_estimator_, model_result.best_score_

In [ ]:
X_def = df.drop(["price"], axis = 1)
y_def = df["price"]

In [ ]:
model = RandomForestRegressor(max_depth=16, max_features='sqrt', n_estimators=650, random_state = 42)
model.fit(X_def, y_def)

In [ ]:
X_test.iloc[0, :].values

In [ ]:
kjlblkj

In [ ]:
import pickle


with open("model_rf.sav", "wb") as file:
    pickle.dump(model, file)

In [ ]:
with open("model_gbr.sav", "rb") as file:
    model = pickle.load(file)

In [ ]:
y_scaler.inverse_transform([model.predict([X_test.iloc[0, :].values])])